version: '2.1'

services:
  todo-service:
    image: todo-service:latest
    build: ./
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8888:8888"
    environment:
      - GIN_MODE=release

  db:
    image: mysql:5.7
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 20s
      timeout: 5s
      retries: 4
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_DATABASE=todo-service